# Generated by Django 2.2.5 on 2020-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200508_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='null', max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
